/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomLookAndFeel.h"
#include "AudioLiveScrollingDisplay.h"
#include "CrossoverComponent.h"

//==============================================================================
/**
*/
class MumuAudioFlangerAudioProcessorEditor  : public AudioProcessorEditor,
                                              public ChangeListener,
                                              Slider::Listener,
                                              Button::Listener,
                                              Timer
{
public:
    MumuAudioFlangerAudioProcessorEditor (MumuAudioFlangerAudioProcessor&);
    ~MumuAudioFlangerAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    
    void timerCallback() override;
    void sliderValueChanged (Slider* sliderThatWasChanged) override;
    void buttonClicked(Button* button) override;
    
    void mouseDown (const MouseEvent &e) override;
    void mouseDrag (const MouseEvent &e) override;
    
    void changeListenerCallback (ChangeBroadcaster *source) override;
    
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MumuAudioFlangerAudioProcessor& processor;
    
    ScopedPointer<LiveScrollingAudioDisplay> liveAudioScroller;
    ScopedPointer<CrossoverComponent> CrossOverWindow;
    
    
    ScopedPointer<Slider> knob1;
    ScopedPointer<Slider> knob2;
    ScopedPointer<Slider> knob3;
    ScopedPointer<Slider> knob4;
    TextButton button1;
    TextButton button2;
    
    CustomLookAndFeel myLookAndFeel;
    
    
    
    
    
    
    
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MumuAudioFlangerAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
